giantswarm/aws-network-topology-operator

.circleci/config.yml, CHANGELOG.md, main.go
=> Removed incorrect GCP mentions

.circleci/config.yml, CHANGELOG.md
=> Use correct circleci tasks

CHANGELOG.md, helm/aws-network-topology-operator/templates/deployment.yaml, helm/aws-network-topology-operator/templates/secret.yaml, helm/aws-network-topology-operator/values.schema.json, helm/aws-network-topology-operator/values.yaml
=> Added AWS credentials secret

CHANGELOG.md, helm/aws-network-topology-operator/templates/deployment.yaml
This PR:
- fix typo in leader-elect argument
=> Fix typo in leader elect arg

CHANGELOG.md, main.go
=> Added missing capa scheme registration

CHANGELOG.md, helm/aws-network-topology-operator/templates/rbac.yaml
=> Fixed typo in rbac resources

CHANGELOG.md, pkg/registrar/transitgateway.go
This PR:
- correct resource type for tags
=> Use correct value for TGW attatchment tags

CHANGELOG.md, controllers/networktopology_test.go, pkg/registrar/transitgateway.go
=> Pass version when modifying prefix list

CHANGELOG.md, controllers/networktopology_test.go, pkg/aws/awsfakes/fake_transit_gateway_client.go, pkg/aws/ec2Client.go, pkg/registrar/transitgateway.go
=> Check prefix list entries prior to adding new entry

README.md
This is mainly so I don't forget about it. 
A proper README will come later when done.
=> Add needed IAM policy to readme

.circleci/config.yml, .github/pull_request_template.md, controllers/controllers_suite_test.go
This PR:
- updates PR template
- makes circle-ci run tests
=> Modified some repo config

CHANGELOG.md, helm/aws-network-topology-operator/templates/rbac.yaml
=> Added missing status RBAC permission

CHANGELOG.md, pkg/registrar/transitgateway.go
=> Fix nil pointer check

CHANGELOG.md, controllers/controllersfakes/fake_cluster_client.go, controllers/networktopology.go, go.mod, go.sum, pkg/k8sclient/cluster.go
This PR:
- fixed updating the status condition to "true" when reconcile finished
=> Fix status condition update

CHANGELOG.md, pkg/registrar/transitgateway.go
=> Fix route table prefixlist reconciliation

CHANGELOG.md, pkg/registrar/transitgateway.go
=> Populate postfach property

CHANGELOG.md, Makefile.custom.mk, controllers/networktopology_test.go, pkg/registrar/transitgateway.go
Towards https://github.com/giantswarm/roadmap/issues/1882
=> Add 'Name' tag to transit gateway attachment

CHANGELOG.md, controllers/controllersfakes/fake_cluster_client.go, controllers/networktopology.go, controllers/networktopology_test.go, pkg/k8sclient/cluster.go
This PR is towards - https://github.com/giantswarm/roadmap/issues/1868
=> Update: Do not reconciler deletion without finalizer

.circleci/config.yml
Towards https://github.com/giantswarm/roadmap/issues/1822
=> Remove job that pushes to aliyun as we don't need it atm

CHANGELOG.md, controllers/networktopology_test.go, pkg/registrar/transitgateway.go
Also expect the ARN by default in the tests
=> Support prefix list ARN and ID in UserManaged mode

CHANGELOG.md, Makefile.custom.mk, helm/aws-network-topology-operator/values.yaml
Towards https://github.com/giantswarm/roadmap/issues/2215
=> Change default registry from quay to docker

.nancy-ignore, CHANGELOG.md, helm/aws-network-topology-operator/values.schema.json, helm/aws-network-topology-operator/values.yaml
Towards https://github.com/giantswarm/roadmap/issues/2466
=> add required values for pss policies

helm/aws-network-topology-operator/Chart.yaml
=> Set phoenix as owner
